webapp/src/Entity/Language.php
<?php declare(strict_types=1);
namespace App\Entity;

use App\Validator\Constraints\Identifier;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use OpenApi\Annotations as OA;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Programming languages in which teams can submit solutions.
 *
 * @ORM\Entity()
 * @ORM\Table(
 *     name="language",
 *     options={"collation"="utf8mb4_unicode_ci", "charset"="utf8mb4", "comment"="Programming languages in which teams can submit solutions"},
 *     indexes={@ORM\Index(name="compile_script", columns={"compile_script"})},
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="externalid", columns={"externalid"}, options={"lengths": {190}}),
 *     })
 * @UniqueEntity("langid")
 * @UniqueEntity("externalid")
 */
class Language extends BaseApiEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", name="langid", length=32, options={"comment"="Language ID (string)"}, nullable=false)
     * @Serializer\Exclude()
     * @Assert\NotBlank()
     * @Assert\NotEqualTo("add")
     * @Identifier()
     */
    protected ?string $langid = null;

    /**
     * @ORM\Column(type="string", name="externalid", length=255, nullable=true,
     *     options={"comment"="Language ID to expose in the REST API"})
     * @Serializer\SerializedName("id")
     * @Serializer\Groups({"Default", "Nonstrict"})
     */
    protected ?string $externalid = null;

    /**
     * @ORM\Column(type="string", name="name", length=255, options={"comment"="Descriptive language name"}, nullable=false)
     * @Serializer\Groups({"Default", "Nonstrict"})
     * @Assert\NotBlank()
     */
    private string $name = '';

    /**
     * @var string[]
     * @ORM\Column(type="json", length=4294967295, name="extensions",
     *     options={"comment"="List of recognized extensions (JSON encoded)"},
     *     nullable=true)
     * @Serializer\Type("array<string>")
     * @Assert\NotBlank()
     */
    private array $extensions = [];

    /**
     * @ORM\Column(type="boolean", name="filter_compiler_files",
     *     options={"comment"="Whether to filter the files passed to the compiler by the extension list.",
     *              "default"="1"},
     *     nullable=false)
     * @Serializer\Groups({"Nonstrict"})
     */
    private bool $filterCompilerFiles = true;

    /**
     * @ORM\Column(type="boolean", name="allow_submit",
     *     options={"comment"="Are submissions accepted in this language?","default"="1"},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private bool $allowSubmit = true;

    /**
     * @ORM\Column(type="boolean", name="allow_judge",
     *     options={"comment"="Are submissions in this language judged?","default"="1"},
     *     nullable=false)
     * @Serializer\Groups({"Nonstrict"})
     */
    private bool $allowJudge = true;

    /**
     * @ORM\Column(type="float", name="time_factor",
     *     options={"comment"="Language-specific factor multiplied by problem run times","default"="1"},
     *     nullable=false)
     * @Serializer\Type("double")
     * @Serializer\Groups({"Nonstrict"})
     * @Assert\GreaterThan(0)
     * @Assert\NotBlank()
     */
    private float $timeFactor = 1;

    /**
     * @ORM\Column(type="boolean", name="require_entry_point",
     *     options={"comment"="Whether submissions require a code entry point to be specified.","default":"0"},
     *     nullable=false)
     * @Serializer\SerializedName("entry_point_required")
     */
    private bool $require_entry_point = false;

    /**
     * @ORM\Column(type="string", name="entry_point_description",
     *     options={"comment"="The description used in the UI for the entry point field."},
     *     nullable=true)
     * @Serializer\SerializedName("entry_point_name")
     * @OA\Property(nullable=true)
     */
    private ?string $entry_point_description = null;

    /**
     * @ORM\ManyToOne(targetEntity="Executable", inversedBy="languages")
     * @ORM\JoinColumn(name="compile_script", referencedColumnName="execid", onDelete="SET NULL")
     * @Serializer\Exclude()
     */
    private ?Executable $compile_executable;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="language")
     * @Serializer\Exclude()
     */
    private Collection $submissions;

    /**
     * @Serializer\VirtualProperty
     * @Serializer\Type("string")
     * @Serializer\SerializedName("compile_executable_hash")
     * @OA\Property(nullable=true)
     */
    public function getCompileExecutableHash(): ?string
    {
        if ($this->compile_executable !== null) {
            return $this->compile_executable->getImmutableExecutable()->getHash();
        } else {
            return null;
        }
    }

    public function setLangid(string $langid): Language
    {
        $this->langid = $langid;
        return $this;
    }

    public function getLangid(): ?string
    {
        return $this->langid;
    }

    public function setExternalid(string $externalid): Language
    {
        $this->externalid = $externalid;
        return $this;
    }

    public function getExternalid(): ?string
    {
        return $this->externalid;
    }

    public function setName(string $name): Language
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getShortDescription(): string
    {
        return $this->getName();
    }

    public function setExtensions(array $extensions): Language
    {
        $this->extensions = $extensions;
        return $this;
    }

    public function getExtensions(): array
    {
        return $this->extensions;
    }

    public function setFilterCompilerFiles(bool $filterCompilerFiles): Language
    {
        $this->filterCompilerFiles = $filterCompilerFiles;
        return $this;
    }

    public function getFilterCompilerFiles(): bool
    {
        return $this->filterCompilerFiles;
    }

    public function setAllowSubmit(bool $allowSubmit): Language
    {
        $this->allowSubmit = $allowSubmit;
        return $this;
    }

    public function getAllowSubmit(): bool
    {
        return $this->allowSubmit;
    }

    public function setAllowJudge(bool $allowJudge): Language
    {
        $this->allowJudge = $allowJudge;
        return $this;
    }

    public function getAllowJudge(): bool
    {
        return $this->allowJudge;
    }

    public function setTimeFactor(float $timeFactor): Language
    {
        $this->timeFactor = $timeFactor;
        return $this;
    }

    public function getTimeFactor(): float
    {
        return $this->timeFactor;
    }

    public function setRequireEntryPoint(bool $requireEntryPoint): Language
    {
        $this->require_entry_point = $requireEntryPoint;
        return $this;
    }

    public function getRequireEntryPoint(): bool
    {
        return $this->require_entry_point;
    }

    public function setEntryPointDescription(?string $entryPointDescription): Language
    {
        $this->entry_point_description = $entryPointDescription;
        return $this;
    }

    public function getEntryPointDescription(): ?string
    {
        return $this->entry_point_description;
    }

    public function setCompileExecutable(?Executable $compileExecutable = null): Language
    {
        $this->compile_executable = $compileExecutable;
        return $this;
    }

    public function getCompileExecutable(): ?Executable
    {
        return $this->compile_executable;
    }

    public function __construct()
    {
        $this->submissions = new ArrayCollection();
    }

    public function addSubmission(Submission $submission): Language
    {
        $this->submissions[] = $submission;
        return $this;
    }

    public function removeSubmission(Submission $submission)
    {
        $this->submissions->removeElement($submission);
    }

    public function getSubmissions(): Collection
    {
        return $this->submissions;
    }

    public function getAceLanguage(): string
    {
        switch ($this->getLangid()) {
            case 'c':
            case 'cpp':
            case 'cxx':
                return 'c_cpp';
            case 'pas':
                return 'pascal';
            case 'hs':
                return 'haskell';
            case 'pl':
                return 'perl';
            case 'bash':
                return 'sh';
            case 'py2':
            case 'py3':
                return 'python';
            case 'adb':
                return 'ada';
            case 'plg':
                return 'prolog';
            case 'rb':
                return 'ruby';
            case 'rs':
                return 'rust';
        }
        return $this->getLangid();
    }
}

webapp/src/Entity/Testcase.php
<?php declare(strict_types=1);
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Stores testcases per problem.
 *
 * @ORM\Entity()
 * @ORM\Table(
 *     name="testcase",
 *     options={"collation"="utf8mb4_unicode_ci", "charset"="utf8mb4", "comment"="Stores testcases per problem"},
 *     indexes={
 *         @ORM\Index(name="probid", columns={"probid"}),
 *         @ORM\Index(name="sample", columns={"sample"})
 *     },
 *     uniqueConstraints={@ORM\UniqueConstraint(name="rankindex", columns={"probid","ranknumber"})})
 */
class Testcase
{
    // Mapping from type to extension
    public const EXTENSION_MAPPING = [
        'input'  => 'in',
        'output' => 'ans',
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="testcaseid", length=4,
     *     options={"comment"="Testcase ID","unsigned"=true},
     *     nullable=false)
     */
    private int $testcaseid;

    /**
     * @ORM\Column(type="string", name="md5sum_input", length=32,
     *     options={"comment"="Checksum of input data","fixed"=true},
     *     nullable=true)
     */
    private ?string $md5sum_input;

    /**
     * @ORM\Column(type="string", name="md5sum_output", length=32,
     *     options={"comment"="Checksum of output data","fixed"=true},
     *     nullable=true)
     */
    private ?string $md5sum_output;

    /**
     * @ORM\Column(type="integer", name="`ranknumber`", length=4,
     *     options={"comment"="Determines order of the testcases in judging",
     *              "unsigned"=true},
     *     nullable=false)
     */
    private int $ranknumber;

    /**
     * @var resource|null
     * @ORM\Column(type="blob", length=4294967295, name="description",
     *     options={"comment"="Description of this testcase"},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private $description;

    private ?string $description_as_string = null;

    /**
     * @ORM\Column(type="string", name="orig_input_filename", length=255,
     *     options={"comment"="Original basename of the input file.","default"=NULL},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private ?string $orig_input_filename;

    /**
     * @ORM\Column(type="string", name="image_type", length=4,
     *     options={"comment"="File type of the image and thumbnail"},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private ?string $image_type;

    /**
     * @ORM\Column(type="boolean", name="sample",
     *     options={"comment"="Sample testcases that can be shared with teams",
     *              "default"="0"},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private bool $sample = false;

    /**
     * @ORM\Column(type="boolean", name="deleted",
     *     options={"comment"="Deleted testcases are kept for referential integrity.",
     *              "default"="0"},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private bool $deleted = false;

    /**
     * @ORM\OneToMany(targetEntity="JudgingRun", mappedBy="testcase")
     * @Serializer\Exclude()
     */
    private Collection $judging_runs;

    /**
     * @ORM\OneToMany(targetEntity="ExternalRun", mappedBy="testcase")
     * @Serializer\Exclude()
     */
    private Collection $external_runs;

    /**
     * We use a OneToMany instead of a OneToOne here, because otherwise this
     * relation will always be loaded. See the commit message of commit
     * 9e421f96691ec67ed62767fe465a6d8751edd884 for a more elaborate explanation.
     *
     * @ORM\OneToMany(targetEntity="TestcaseContent", mappedBy="testcase", cascade={"persist"}, orphanRemoval=true)
     * @Serializer\Exclude()
     */
    private Collection $content;

    /**
     * @ORM\ManyToOne(targetEntity="Problem", inversedBy="testcases")
     * @ORM\JoinColumn(name="probid", referencedColumnName="probid", onDelete="CASCADE")
     * @Serializer\Exclude()
     */
    private ?Problem $problem;

    public function __construct()
    {
        $this->judging_runs  = new ArrayCollection();
        $this->external_runs = new ArrayCollection();
        $this->content       = new ArrayCollection();
    }

    public function getTestcaseid(): int
    {
        return $this->testcaseid;
    }

    public function setMd5sumInput(string $md5sumInput): Testcase
    {
        $this->md5sum_input = $md5sumInput;
        return $this;
    }

    public function getMd5sumInput(): string
    {
        return $this->md5sum_input;
    }

    public function setMd5sumOutput(string $md5sumOutput): Testcase
    {
        $this->md5sum_output = $md5sumOutput;
        return $this;
    }

    public function getMd5sumOutput(): string
    {
        return $this->md5sum_output;
    }

    public function setRank(int $rank): Testcase
    {
        $this->ranknumber = $rank;
        return $this;
    }

    public function getRank(): int
    {
        return $this->ranknumber;
    }

    /**
     * @param resource|string $description
     */
    public function setDescription($description): Testcase
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return resource|string|null
     */
    public function getDescription(bool $asString = false)
    {
        if ($asString && $this->description !== null) {
            if ($this->description_as_string === null) {
                $this->description_as_string = stream_get_contents($this->description);
            }
            return $this->description_as_string;
        }
        return $this->description;
    }

    public function setOrigInputFilename(string $origInputFilename): Testcase
    {
        $this->orig_input_filename = $origInputFilename;
        return $this;
    }

    public function getOrigInputFilename(): ?string
    {
        return $this->orig_input_filename;
    }

    public function setImageType(string $imageType): Testcase
    {
        $this->image_type = $imageType;
        return $this;
    }

    public function getImageType(): ?string
    {
        return $this->image_type;
    }

    public function setSample(bool $sample): Testcase
    {
        $this->sample = $sample;
        return $this;
    }

    public function setDeleted(bool $deleted): Testcase
    {
        $this->deleted = $deleted;
        return $this;
    }

    public function getSample(): bool
    {
        return $this->sample;
    }

    public function getDeleted(): bool
    {
        return $this->deleted;
    }

    public function addJudgingRun(JudgingRun $judgingRun): Testcase
    {
        $this->judging_runs[] = $judgingRun;
        return $this;
    }

    public function removeJudgingRun(JudgingRun $judgingRun): Testcase
    {
        $this->judging_runs->removeElement($judgingRun);
        return $this;
    }

    public function getJudgingRuns(): Collection
    {
        return $this->judging_runs;
    }

    /**
     * Gets the first judging run for this testcase.
     *
     * This is useful when this testcase is joined to a single run to get code completion in Twig templates.
     */
    public function getFirstJudgingRun(): ?JudgingRun
    {
        return $this->judging_runs->first() ?: null;
    }

    /**
     * Gets the first external run for this testcase.
     *
     * This is useful when this testcase is joined to a single external run to get code completion in Twig templates.
     */
    public function getFirstExternalRun(): ?ExternalRun
    {
        return $this->external_runs->first() ?: null;
    }

    public function setContent(?TestcaseContent $content): Testcase
    {
        $this->content->clear();
        $this->content->add($content);
        $content->setTestcase($this);

        return $this;
    }

    public function getContent(): ?TestcaseContent
    {
        return $this->content->first() ?: null;
    }

    public function setProblem(?Problem $problem = null): Testcase
    {
        $this->problem = $problem;
        return $this;
    }

    public function getProblem(): ?Problem
    {
        return $this->problem;
    }

    public function addExternalRun(ExternalRun $externalRun): Testcase
    {
        $this->external_runs[] = $externalRun;
        return $this;
    }

    public function removeExternalRun(ExternalRun $externalRun)
    {
        $this->external_runs->removeElement($externalRun);
    }

    public function getExternalRuns(): Collection
    {
        return $this->external_runs;
    }

    public function getDownloadName(): string
    {
        if ($this->getOrigInputFilename()) {
            return $this->getOrigInputFilename();
        }

        return sprintf('p%d.t%d', $this->getProblem()->getProbid(), $this->getRank());
    }
}

webapp/templates/jury/check_judgings.html.twig
{% extends "jury/base.html.twig" %}
{% import _self as checkJudgings %}
{% import "jury/jury_macros.twig" as macros %}

{% block title %}Judging verifier - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.table_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Judging verifier</h1>

    <p>
        {{ numChecked }} submissions checked:
        {{ unexpected | length }} unexpected results,
        {% if verifyMultiple %}
            {{ multiple | length }} automatically verified (multiple outcomes),
        {% else %}
            {{ multiple | length }} to check manually,
        {% endif %}
        {{ verified | length }} automatically verified
        <br>
        {{ numUnchecked }} submissions not checked:
        {{ earlier | length }} verified earlier,
        {{ nomatch | length }} without magic string
    </p>

    {% macro verifyResults(id, header, results, collapse) %}
        {% if results is not empty %}
            <h2><a class="collapse-link" href="javascript:collapse('#detail{{ id }}')">{{ header }}</a></h2>
            <ul id="detail{{ id }}"{% if collapse | default(false) %} class="d-none"{% endif %}>
                {% for submitId,result in results %}
                    <li><a href="{{ path('jury_submission', {'submitId': submitId}) }}">s{{ submitId }}</a>
                    {% if result.files is defined and result.files|length > 0 %}
                        ({% for file in result.files[:3] %}
                            <code>{{ file.filename }}</code>
                        {% endfor %})
                    {% endif %}
                    {% if id == 'unexpected' %}
                        has unexpected result '{{ result.actual }}', should be one of: {{ result.expected|join(', ') }}
                    {% elseif id == 'multiple' and result.verified %}
                        verified as {{ result.actual }} out of multiple possible outcomes ({{ result.expected|join(', ') }})
                    {% elseif id == 'multiple' %}
                        is judged as {{ result.actual }} but has multiple possible outcomes ({{ result.expected|join(', ') }})
                    {% elseif id == 'verified' %}
                        verfied as '{{ result.actual }}'
                    {% elseif id == 'nomatch' %}
                        expected results unknown, leaving submission unchecked
                    {% elseif id == 'earlier' %}
                        already verified earlier
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endmacro %}

    {{ checkJudgings.verifyResults('unexpected', 'Unexpected results', unexpected) }}
    {% if verifyMultiple %}
        {{ checkJudgings.verifyResults('multiple', 'Automatically verified (multiple outcomes)', multiple, true) }}
    {% else %}
        {{ checkJudgings.verifyResults('multiple', 'Check manually', multiple) }}
        {% if multiple is not empty %}
            <form action="{{ path('jury_judging_verifier') }}" method="post">
                <input type="hidden" name="verify_multiple" value="1">
                <p>
                    Verify all multiple outcome submissions:
                    <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i> Verify</button>
                </p>
            </form>
        {% endif %}
    {% endif %}
    {{ checkJudgings.verifyResults('verified', 'Automatically verified', verified, true) }}
    {{ checkJudgings.verifyResults('earlier', 'Verified earlier', earlier, true) }}
    {{ checkJudgings.verifyResults('nomatch', 'Without magic string', nomatch, true) }}

{% endblock %}

webapp/templates/jury/problem_testcases.html.twig
{% extends "jury/base.html.twig" %}
{% import "jury/jury_macros.twig" as macros %}

{% block title %}Testcases for p{{ problem.probid }} - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.table_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Testcases for p{{ problem.probid }} - {{ problem.name }}</h1>

    <div class="mb-2">
        <a href="{{ path('jury_problem', {'probId': problem.probid}) }}">Back to problem p{{ problem.probid }}</a>
    </div>

    <form method="post" enctype="multipart/form-data">

    {% if testcases is empty %}
        <p class="nodata">No testcase(s) yet.</p>
    {% else %}
        <table class="table table-sm table-striped table-hover testcases">
            <thead>
            <tr>
                {% if allowEdit %}
                    <th></th>
                {% endif %}
                <th class="testrank">#</th>
                <th class="testsample">sample</th>
                <th>download</th>
                <th>size</th>
                <th>md5</th>
                {% if allowEdit %}
                    <th>upload new</th>
                {% endif %}
                <th>description / image</th>
            </tr>
            </thead>
            <tbody>
            {% for rank, testcase in testcases %}
                <tr>
                    {% if allowEdit %}
                        <td rowspan="2">
                            <a href="{{  path('jury_testcase_delete', {'testcaseId': testcase.testcaseid}) }}"
                               title="delete testcase {{ testcase.testcaseid }}"
                               onclick="confirm('Proceed with the deletion of testcase {{ testcase.testcaseid }}?');">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    {% endif %}
                    <td rowspan="2" class="testrank">
                        {% if allowEdit %}
                            <a href="{{ path('jury_problem_testcase_move', {'probId': problem.probid, 'rank': testcase.rank, 'direction': 'up'}) }}"
                               title="Move testcase up"><i class="fas fa-arrow-up"></i></a><br>
                        {% endif %}
                        {{ testcase.rank }}
                        {% if allowEdit %}
                            <br>
                            <a href="{{ path('jury_problem_testcase_move', {'probId': problem.probid, 'rank': testcase.rank, 'direction': 'down'}) }}"
                               title="Move testcase down"><i class="fas fa-arrow-down"></i></a>
                        {% endif %}
                    </td>
                    <td rowspan="2" class="testsample">
                        <input type="checkbox" name="sample[{{ testcase.rank }}]" value="sample"
                               {% if testcase.sample %}checked{% endif %} />
                    </td>
                    <td class="filename">
                        <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'input'}) }}">
                            {{ testcase.downloadName }}.{{ extensionMapping.input }}
                        </a>
                    </td>
                    <td class="size">
                        {{ testcaseData[testcase.rank].input_size | printSize }}
                    </td>
                    <td class="md5 small">
                        {{ testcase.md5sumInput }}
                    </td>
                    {% if allowEdit %}
                        <td><div class="custom-file">
                            <input type="file" class="custom-file-input" name="update_input[{{ testcase.rank }}]" id="update_input_{{testcase.rank}}">
                            <label class="custom-file-label text-truncate text-muted" for="update_input_{{testcase.rank}}">new input file</label>
                        </div></td>
                    {% endif %}
                    <td class="testdesc">
                        <span class="testcase-description">{{ testcase.description(true) | descriptionExpand }}</span>
                        {% if allowEdit %}
                            <textarea class="d-none form-control testcase-description-field" name="description[{{ testcase.rank }}]">{{ testcase.description(true) }}</textarea>
                            <button type="button" class="float-right testcase-edit-description btn btn-secondary btn-sm">Edit</button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="filename">
                        <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'output'}) }}">
                            {{ testcase.downloadName }}.{{ extensionMapping.output }}
                        </a>
                    </td>
                    <td class="size">
                        {{ testcaseData[testcase.rank].output_size | printSize }}
                    </td>
                    <td class="md5 small">
                        {{ testcase.md5sumOutput }}
                    </td>
                    {% if allowEdit %}
                        <td><div class="custom-file">
                            <input type="file" class="custom-file-input" name="update_output[{{ testcase.rank }}]" id="update_output_{{testcase.rank}}">
                            <label class="custom-file-label text-truncate text-muted" for="update_output_{{testcase.rank}}">new output file</label>
                        </div></td>
                    {% endif %}
                    <td class="testimage">
                        {% if testcaseData[testcase.rank].image_size > 0 %}
                            <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'image'}) }}">
                                <span class="filename">p{{ problem.probid }}.t{{ testcase.rank }}.{{ testcaseData[testcase.rank].image_type }}</span>
                            </a>
                            {% if allowEdit %}
                            &nbsp;
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="update_image[{{ testcase.rank }}]" id="update_image_{{testcase.rank}}">
                                <label class="custom-file-label text-truncate text-muted" for="update_image_{{testcase.rank}}">replace image</label>
                            </div>
                            {% endif %}
                        {% else %}
                            {% if allowEdit %}
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="update_image[{{ testcase.rank }}]" id="update_image_{{testcase.rank}}">
                                <label class="custom-file-label text-truncate text-muted" for="update_image_{{testcase.rank}}">add an image</label>
                            </div>
                            {% else %}
                            <span class="nodata">No image</span>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% if allowEdit %}
        <h2>Create new testcase</h2>

        <div class="form-row">
            <div class="form-group col-sm-4">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="add_input" id="add_input">
                    <label class="custom-file-label text-truncate text-muted" for="add_input">Input testdata</label>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-4">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="add_output" id="add_output">
                    <label class="custom-file-label text-truncate text-muted" for="add_output">Output testdata</label>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-4">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="add_sample" name="add_sample">
                    <label class="custom-control-label" for="add_sample">Sample testcase</label>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-4">
                <label for="add_desc">Description</label>
                <textarea name="add_desc" id="add_desc" rows="5" class="form-control"></textarea>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-4">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="add_image" id="add_image">
                    <label class="custom-file-label text-truncate text-muted" for="add_image">Image</label>
                </div>
            </div>
        </div>

        <input type="submit" class="btn btn-primary" value="Submit all changes">
    {% endif %}

    </form>

    <script>
        $(function() {
            $('.testcase-edit-description').on('click', function() {
                var $button = $(this);
                var $description = $button.parent().find('.testcase-description');
                var $descriptionInput = $button.parent().find('.testcase-description-field');

                if ($description.hasClass('d-none')) {
                    $description.removeClass('d-none');
                    $descriptionInput.addClass('d-none');
                    $button.text('Edit');
                    $descriptionInput.val($description.text());
                } else {
                    $description.addClass('d-none');
                    $descriptionInput.removeClass('d-none');
                    $button.text('Cancel');
                }
            });
        });
    </script>

{% endblock %}